config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
             uniqueness: { case_sensitive: false }, 
             length: { minimum: 3, maximum: 25 } 
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, 
              uniqueness: { case_sensitive: false },
              format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end
    
    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def index
       @articles = Article.paginate(page: params[:page], per_page: 5) 
    end
    
    def new
        @article = Article.new
    end
    
    def edit
    end
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end
    
    def update
       if @article.update(article_params)
           flash[:success] = "Article was successfully updated"
           redirect_to article_path(@article)
       else
           render 'edit'
       end
    end
    
    def show
    end
    
    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted"
        redirect_to articles_path
    end
    
    private
     def set_article
         @article = Article.find(params[:id])
     end
    
     def article_params
         params.require(:article).permit(:title, :description, category_ids: [])
     end
     
     def require_same_user
         if current_user != @article.user and !current_user.admin?
             flash[:danger] = "You can only edit or delete your own articles"
             redirect_to root_path
         end
     end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    
    def index
       @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end
    
    def edit
        @category = Category.find(params[:id]) 
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
           flash[:success] = "Name was successfully updated"
           redirect_to category_path(@category)
        else
            render 'edit'
        end
    end
    
    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end
    
    private
    def category_params
        params.require(:category).permit(:name)
    end
    
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
           flash[:danger] = "Only admins can perform that action"
           redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
       redirect_to articles_path if logged_in?
    end
    
    def about
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   
   def new
   
   end 
    
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information"
           render 'new' 
        end
    end
    
    def destroy
       session[:user_id] = nil
       flash[:success] = "You have logged out"
       redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    
    def index
       @users = User.paginate(page: params[:page], per_page: 5) 
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the alpha blog #{@user.username}"
            redirect_to articles_path
        else
           render 'new' 
        end
    end
    
    def edit
    end
    
    def update
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end
    
    def show
       @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end
    
    def destroy
       @user = User.find(params[:id])
       @user.destroy
       flash[:danger] = "User and all articles created by user have been deleted"
       redirect_to users_path
    end
    
    private
    def user_params
       params.require(:user).permit(:username, :email, :password) 
    end
    def set_user
        @user = User.find(params[:id])
    end
    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end
    def require_admin
        if logged_in? and !current_user.admin?
           flash[:danger] = "Only admin users can perform that action"
           redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
       gravatar_id = Digest::MD5::hexdigest(user.email.downcase) 
       size = options[:size]
       gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
       image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <div class="card">
            <div class="card-body">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class="article-body">
                    <%= truncate(article.description, length: 100) %>
                    <div class="article-meta-details">
                        <small>Created By: <%= article.user.username if article.user%>,
                                           <%= time_ago_in_words(article.created_at) %> ago,
                                           last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div>
                </div>
                <% if article.categories.any? %>
                    <p>Categories: <%= render article.categories %></p>
                <% end %>
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                <div class="article-actions">
                    <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-sm btn-primary" %> 
                    <%= link_to "Delete this article", article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete the article?"}, class: "btn btn-sm btn-danger" %>
                </div>
                <% end %>
            </div>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>
    <div class="container">
        <div class='col-sm-12'>
        <%= form_for @article do |f| %>
        <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
        </div>
        <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
                </div>
        </div>
        <div class="form-group row">
                <div class="col-sm-8 offset-sm-2">
                    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                    <% end %>
                </div>
        </div>
        <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <%= f.submit class:"btn btn-primary btn-md" %>
                </div>
        </div>
        <% end %>
        <div class="col-sm-5 offset-sm-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
        </div>
    </div>

app/views/articles/edit.html.erb
<h1 align="center">Edit An Existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing All Articles</h1>
<div align="center">
    <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create A New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="card col-sm-8 offset-sm-2">
    <div class="card-body">
    <% if @article.user %>
    <ul class="listing">
        <div class="container">
            <div class="row center">
                <div class="col-md-4 offset-md-4">
                    <li>Created by:</li>
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class="article-title">
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>
                    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
                </div>
            </div>
        </div>
    </ul>
    <% end %>
    <div class="card-body">
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
    <% if @article.categories.any? %>
        <p>Categories:  <%= render @article.categories %></p>
    <% end %>
    <div class="article-actions">
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-sm btn-primary" %> 
        <%= link_to "Delete this article", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete the article?"}, class: "btn btn-sm btn-danger" %>
        <% end %>
        <%= link_to "View all articles", articles_path, class: "btn btn-sm btn-success" %>
    </div>
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>
   
        <%= form_for @category do |f| %>
        <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    <%= f.label :name %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
                </div>
        </div>
        <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <%= f.submit class:"btn btn-primary btn-md" %>
                </div>
        </div>
        <% end %>
        <div class="col-sm-5 offset-sm-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>

<div align="center">
<%= will_paginate @categories %>
    <% @categories.each do |category| %>
        <ul class="listing">
            <div class="container">
                <div class="row">
                    <div class="card col-md-4 offset-md-4">
                        <li class="article-title">
                            <%= link_to "#{category.name}", category_path(category) %>
                        </li>
                        <li><small><%= pluralize(category.articles.count, "article") %></small></li>
                    </div>
                </div>
            </div>
        </ul>
    <% end %>
<%= will_paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
    <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
    <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; 2020 Justin Gilbert
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-10 offset-sm-1"> 
            <% flash.each do |name, msg| %>
                <div class='alert alert-<%= "#{name}" %> alert-dismissible fade show' role="alert">
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                </div>
            <% end %>
        </div>
    </div>
</div>

    

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <%= link_to "AlphaBlog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "Articles", articles_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
      <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item"><%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %></li>
      <% else %>
      <li class="nav-item"><%= link_to 'Log In', login_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to 'Sign up', signup_path, class: "nav-link" %></li>
      <% end %>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
          <% Category.all.each do |category| %>
          <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
          <% end %>
          <% if logged_in? and current_user.admin? %>
          <div class="dropdown-divider"></div>
          <div><%= link_to "Create New Category", new_category_path, class: "dropdown-item" %></div>
          <div class="dropdown-divider"></div>
          <% end %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/home.css">
    <title>Alpha Blog</title>
  </head>
  <body>
    <header id="main-header">
      <div class="container">
        <h1>Alpha-Blog About Page</h1>
      </div>
    </header>
    <nav>
    <%= link_to 'Home', root_path %>
    </nav>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur quis consequat sem, consectetur tincidunt tortor. Nulla vel blandit erat, dictum placerat enim. Vestibulum porttitor enim quis quam mollis, quis bibendum arcu fermentum. Aliquam placerat arcu et lacinia pharetra. Fusce pretium lorem vel elit porta faucibus. Nunc luctus risus id metus rutrum, ac tristique diam placerat. Praesent consequat in dui molestie elementum. Fusce quis urna felis. Ut maximus iaculis libero ac tempor. Sed congue vitae nisi non auctor. Ut dignissim porta lectus, volutpat consequat neque. Praesent in mi non nunc venenatis facilisis. Nunc lacus sapien, egestas non gravida non, egestas nec dui. Suspendisse sit amet orci ac mauris consequat fringilla ut sit amet nisi.

Nulla a felis diam. Sed blandit aliquam turpis, malesuada imperdiet orci elementum in. Aliquam facilisis mattis lacus, et egestas ante convallis ac. Aliquam hendrerit augue ut nisi mollis luctus. Phasellus ac turpis lobortis, feugiat odio et, feugiat enim. Quisque mattis mauris mattis tempor porta. Nullam posuere est vitae risus porttitor, non aliquet lectus tristique.</p>
    <footer id="main-footer">
      <p>Copyright &copy; 2020 Justin Gilbert</p>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron" >
  <h1>ALPHA BLOG</h1>
  <%= link_to "Sign up now", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
    <div class="col-sm-8 offset-sm-2">
        <div class="alert alert-danger" role="alert">
            <div class="alert-heading">
                <h4 class="alert-title">
                    <%= pluralize(obj.errors.count, "error") %>
                    prohibited this article from being saved:
                </h4>
                <div class="alert-body">
                    <ul>
                        <% obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>
   
   
    <div class="container">
        <div class='col-sm-12'>
        <%= form_for @user do |f| %>
        <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    <%= f.label :username %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
                </div>
        </div>
        <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    <%= f.label :email %>
                </div>
                <div class="col-sm-8">
                    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
                </div>
        </div>
        <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    <%= f.label :password %>
                </div>
                <div class="col-sm-8">
                    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
                </div>
        </div>
        <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <%= f.submit(@user.new_record? ? "Signup" : "Update Account", class:"btn btn-primary btn-md") %>
                </div>
        </div>
        <% end %>
        <div class="col-sm-5 offset-sm-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
        </div>
    </div>

app/views/users/edit.html.erb
<h1 align="center">Edit your Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div align="center">
<%= will_paginate %>
<% @users.each do |user| %>
    <ul class="listing">
        <div class="container">
            <div class="row">
                <div class="card col-md-4 offset-md-4">
                    <li><%= link_to gravatar_for(user), user_path(user) %></li>
                    <li class="article-title">
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
                    <% if logged_in? and current_user.admin? %>
                        <li><%= link_to "Delete this user", user_path(user), method: :delete, 
                        data: { confirm: "Are you sure you want to delete the user and all their articles?" } %></li>
                    <% end %>
                </div>
            </div>
        </div>
    </ul>
<% end %>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for AlphaBlog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s Page</h1>
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 center">
            <%= gravatar_for @user, size: 150 %>
        </div>
    </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
    <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
    <%= will_paginate @user_articles %>
</div>